import fc from "fast-check";

export const globalHTMLAttrArb = fc.record(
  {
    accessKey: fc.array(fc.char()).map((arr) => arr.join(" ")),
    // contentEditable is not supported in JSDom, do not comment out the line below if you don't want to waste your time...
    // contentEditable: fc.boolean(),
    dir: fc.constantFrom("ltr", "rtl", "auto"),
    draggable: fc.boolean(),
    hidden: fc.boolean(),
    id: fc.hexaString(),
    lang: fc.constantFrom("en-US", "en-CA", "fr-FR", "de-DE", "de-CH"),
    tabIndex: fc.integer(),
    title: fc.string(),
  },
  { withDeletedKeys: true }
);

export const basicHTMLElement = [
  "address",
  "article",
  "aside",
  "footer",
  "header",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hgroup",
  "main",
  "nav",
  "section",
  "blockquote",
  "dd",
  "div",
  "dl",
  "dt",
  "figcaption",
  "figure",
  "hr",
  "li",
  "ol",
  "p",
  "pre",
  "ul",
  "a",
  "abbr",
  "b",
  "bdi",
  "bdo",
  "br",
  "cite",
  "code",
  "data",
  "dfn",
  "em",
  "i",
  "kbd",
  "mark",
  "q",
  "s",
  "samp",
  "small",
  "span",
  "strong",
  "sub",
  "sup",
  "time",
  "u",
  "var",
  "wbr",
  "area",
  "audio",
  "map",
  "track",
  "video",
  "embed",
  "iframe",
  "object",
  "param",
  "picture",
  "source",
  "del",
  "ins",
  "button",
  "img",
];
